Libraries practice

Creating NumPy Arrays

In [2]:
import numpy as np
# 1D array
arr1 = np.array([10,20,30,40,50])
print(f"1D array is {arr1}")
# 2D array
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"2D array is {arr2}")
#3D array
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(f"3D array is {arr3}")

1D array is [10 20 30 40 50]
2D array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
3D array is [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


 Array Shape and Reshaping

In [3]:
arr = np.arange(1,13)
print(f"Orginal array {arr}")
# Reshape into (3, 4)
reshaped_array_1 = arr.reshape(3,4)
print(f"Reshaped array into (3,4) {reshaped_array_1}")
# Reshape into (2,6)
reshaped_array_2 = arr.reshape(2,6)
print(f"Reshaped array into (2,6) : {reshaped_array_2}")
# Reshape into (6,2)
reshaped_array_3 = arr.reshape(6,2)
print(f"Reshaped array into (6,2) ", reshaped_array_3)
# Get shape
print("shape of 3 rows and 4 columns: ", reshaped_array_1.shape)

Orginal array [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array into (3,4) [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array into (2,6) : [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Reshaped array into (6,2)  [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
shape of 3 rows and 4 columns:  (3, 4)


Basic Mathematical Operations

In [4]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,6])

# Addition
sum_arr = arr1 + arr2
print(f"Element wise addition is \n {sum_arr}")
# Multiplication
product_arr = arr1 * arr2
print(f"Element wise product is \n {product_arr}")
# Scalar Multiplication 
scalar_mul = arr1 * 3
print(f"Scalar multiplication \n {scalar_mul}")

Element wise addition is 
 [ 6  8 10 10]
Element wise product is 
 [ 5 12 21 24]
Scalar multiplication 
 [ 3  6  9 12]


Statistical operations

In [5]:
data = np.array([10,20,30,40,50])
# Mean
mean = np.mean(data)
print("Mean value is : ",mean)
# Median
median = np.median(data)
print("Median value is : ",median)
# Standard Deviation
std_dev = np.std(data)
print("Standard deviation is : ",std_dev)

Mean value is :  30.0
Median value is :  30.0
Standard deviation is :  14.142135623730951


Creating Data with Pandas

In [6]:
import pandas as pd
# Create DataFrame from dictionary
data = {
    'column 1': [1,2,3],
    'column 2': [4,5,6],
    'column 3': [7,8,9]
}
df = pd.DataFrame(data)
print("Data Frame :\n",df)

# Create DataFrame from NumPy array
arr = np.arange(1,16).reshape(5,3)
df2 = pd.DataFrame(arr, columns= ['A', 'B','C'])
print("Data Frame :\n",df2)

Data Frame :
    column 1  column 2  column 3
0         1         4         7
1         2         5         8
2         3         6         9
Data Frame :
     A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15


In [7]:
import pandas as pd
number_df = pd.DataFrame(np.arange(1,90,3).reshape(10,3),  # np.arange(start, stop, step) generates an array of evenly spaced values.
                         index=["A","B","C","D","E","F","G","H","I","J"],
                         columns= ['col 1', 'col 2', 'col 3'])
print(number_df)

   col 1  col 2  col 3
A      1      4      7
B     10     13     16
C     19     22     25
D     28     31     34
E     37     40     43
F     46     49     52
G     55     58     61
H     64     67     70
I     73     76     79
J     82     85     88


In [8]:
# Selecting rows 1,3,5 and columns 1 and 2
number_df.iloc[[1,3,5], [1,2]]

col 2  col 3
B     13     16
D     31     34
F     49     52

In [9]:
# shows true to the value at the position if it is more than 50
result = number_df > 50
result

col 1  col 2  col 3
A  False  False  False
B  False  False  False
C  False  False  False
D  False  False  False
E  False  False  False
F  False  False   True
G   True   True   True
H   True   True   True
I   True   True   True
J   True   True   True

In [10]:
# Shows you values only more than 50 and NaN if the value is not more than 50
result = number_df > 50
number_df[result]

col 1  col 2  col 3
A    NaN    NaN    NaN
B    NaN    NaN    NaN
C    NaN    NaN    NaN
D    NaN    NaN    NaN
E    NaN    NaN    NaN
F    NaN    NaN   52.0
G   55.0   58.0   61.0
H   64.0   67.0   70.0
I   73.0   76.0   79.0
J   82.0   85.0   88.0

In [11]:
# Turn all the numbers which are greater than 50 into 0
number_df[number_df > 50] = 0
number_df

col 1  col 2  col 3
A      1      4      7
B     10     13     16
C     19     22     25
D     28     31     34
E     37     40     43
F     46     49      0
G      0      0      0
H      0      0      0
I      0      0      0
J      0      0      0

Indexing with iloc

In [12]:
# Create a DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})
print(df)
# Select the first row
row1 = df.iloc[0]
print(f"First row is\n{row1}")
# Select the first two rows
row2 = df.iloc[0:2]
print(f"First 2 rows are\n{row2}")
# Select the value at the first row and second column
row_col_value = df.iloc[0,1]
print(f"value at the first row and second column is {row_col_value}")
# Slicing rows and columns
sub_set = df.iloc[1:3, 0:2]
print(f"Sub set is\n{sub_set}")

   A  B
0  1  4
1  2  5
2  3  6
First row is
A    1
B    4
Name: 0, dtype: int64
First 2 rows are
   A  B
0  1  4
1  2  5
value at the first row and second column is 4
Sub set is
   A  B
1  2  5
2  3  6
